library:
    resource: "@LibraryBundle/Controller/"
    type:     annotation
    prefix:   /

storage_api:
    resource: "@StorageApiBundle/Controller/"
    type:     annotation
    prefix:   /api/v1/

library_storage:
    resource: "@LibraryStorageBundle/Controller/"
    type:     annotation
    prefix:   /library1

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
