storage_api:
    resource: "@StorageApiBundle/Controller/"
    type:     annotation
    prefix:   /api/

library_storage:
    resource: "@LibraryStorageBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
