services:
#    storage_api.example:
#        class: StorageApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor

